Update dependencies to avoiding pinning to old Rust package versions
holochain/holochain-serialization pull request #35
Opened 2020-12-17 22:35 UTC by pjkundert

o Specify a "1.0" version for syn and quote, to allow upstream packages
  to specify newer versions; major/minor version compatibility should
  be sufficiently stable.
o Update shrinkwraprs to not pin an old syn version.

2020-12-17 22:37 UTC, pjkundert commented
Also, make sure you merge https://github.com/freesig/observability/pull/1, to avoid pinning observability to an old version of holochain-serialization, too.

2020-12-22 04:23 UTC, freesig requested changes
I like the general idea of this but I think we should use the [release procedure](https://docs.holochain.love/docs/release/) instead of manually bumping crate versions. Not so sure about syn and quote not breaking because it's possible something under them breaks and then we have no way to change the version from holochain

2020-12-22 04:23 UTC, freesig commented on crates/holochain_json_api/Cargo.toml
> +version = "0.0.47"
There's a nix script for doing this version bump and publishing. Better to use that then manually bumping I think.

2020-12-22 16:02 UTC, pjkundert commented
Closed in favor of https://github.com/holochain/holochain-serialization/pull/36

2020-12-22 16:02 UTC, closed without merging